### ISSUE TITLE
Update for changes in remark

### ISSUE THREAD

**Issue by wooorm** [remarkjs/remark-external-links#1]
Hi! 👋

remark just changed: you can read more about the changed [here][1].

That means that this plugin doesn’t work with the latest remark. If you get around to updating, use the previously mentioned changelog for help, but feel free to respond below or ask questions on [Gitter][2]!

[1]: https://github.com/wooorm/remark/releases/tag/7.0.0
[2]: https://gitter.im/wooorm/remark
[3]: https://github.com/wooorm/remark/blob/master/doc/plugins.md#list-of-plugins

**Comment by xuopled** [comment]
Hi @wooorm, sorry for the delay. Do you have updating documentation somewhere ?

**Comment by wooorm** [comment]
No problem!

The link I posted above contains some info to further resources!

**Comment by xuopled** [comment]
Special thanks to @fand. 
@wooorm v2.0.0 should be compatible with the latest remark.

I close the issue.
Feel free to re-open it if something is wrong
