### ISSUE TITLE
plugin overwrites node data.hProperties set by other remark plugins

### ISSUE THREAD

**Issue by vadimgo** [remarkjs/remark-external-links#14]
When using gatsby-remark-external-links in combination with a plugin also setting node data.hProperties, such as gatsby-remark-default-html-attrs, the attributes set by the other plugin (when it runs earlier in the build process) get lost.

In index.js for gatsby-remark-external-links, the code

```javascript
        link.data = {
          hProperties: {}
        };
```

should change to

```javascript
      if (!link.data.hProperties) {
        link.data = {
          hProperties: {}
        };
      }
```

**Comment by wooorm** [comment]
This was fixed in >=3.0.0
