### ISSUE TITLE
Pass additional properties to a and span elements

### ISSUE THREAD

**Issue by iloveip** [remarkjs/remark-external-links#15]
I would like to be able to pass additional properties to the link itself and the `span` element, like `className` (for both elements) and `role: 'img'` for `span`. 

At the moment I had to add another `span` inside the given `span` to do this:
`content: h('span', {role: 'img', class: 'anticon'}, s('svg',...))`. And I can't style the link, as there is no way to pass `className` to it.

**Comment by wooorm** [comment]
👋

Could you tell us more about the higher-level thing you want to achieve? Maybe that’s better done in a custom-made plugin?

**Comment by iloveip** [comment]
I need to have something like this:

```
<a href="" target="_blank" rel="nofollow noopener noreferrer" class="external">link_title
  <span role="img" class="anticon">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="64 64 896 896" focusable="false" width="1em" height="1em" fill="currentColor" aria-hidden="true">
      <path></path>
    </svg>
  </span>
</a>
```

So I need to be able to pass `className` to `a` and to `span`. I also need to pass `role="img"` to `span`.

**Comment by wooorm** [comment]
Might your case also in the end need for example classes or icons for local/internal links (`#heading` or `/same/site`)?

**Comment by iloveip** [comment]
No, we use icons only for external links. Internal links are managed by [gatsby-plugin-catch-links](https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/).

**Comment by wooorm** [comment]
Would the CSS selector `a[rel]` or `a[target]` be a potential solution to use instead of the class?

**Comment by iloveip** [comment]
Yes, `a[rel]` works.

**Comment by wooorm** [comment]
Ah great!!

For the properties, that can be done! Would you be interested in working on a PR for that? Something like:

```js
  contentProperties = settings.contentProperties || {}

  // ...

  data: {hName: 'span', hProperties: extend(true, contentProperties), hChildren: extend(true, content)}
```

In `index.js`?

**Comment by iloveip** [comment]
Yes, sure, I've created the PR above. But I'm new to programming, so I don't really know what's the right way to do it.

**Comment by wooorm** [comment]
Closed by GH-16.
