### ISSUE TITLE
Add to remarkjs npm org

### ISSUE THREAD

**Issue by wooorm** [remarkjs/remark-external-links#3]
Hey! I just reworked some of the code here to align it more to other remarkjs projects, similar options, but also to remove babel. I applied some fixes, added 100% coverage, reworded the readme and some config files. Etc.

Anyway, could you add me as a collaborator on npm? I’ll make sure to add this project to the remarkjs org on npm, so that we can have the community maintain it!

I’ll cut a new major release if you’re okay with all this?

👋

**Comment by wooorm** [comment]
@xuopled ping!

**Comment by xuopled** [comment]
Hey @wooorm! Sorry I missed your first call.

I just added you as maintainer on npm.
Tell me if it's ok for you now

**Comment by wooorm** [comment]
Thanks! Published!
