### ISSUE TITLE
is it possible to exclude fragment anchors?

### ISSUE THREAD

**Issue by chantastic** [remarkjs/remark-external-links#4]
This plugin is great.
Thanks for making it.

Is it possible to exclude fragment anchors?
As it is now, all my fragment links are getting the external link treatment.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/658360/47247066-2438a200-d3b6-11e8-9ba8-f4f570eea1aa.png">

thanks!

**Comment by wooorm** [comment]
@chantastic PRs welcome! Somewhere [here](https://github.com/remarkjs/remark-external-links/blob/5cc2fed9a24b70b45a0e8007bc98fa7c3c0a52b2/index.js#L29) I think?

**Comment by wooorm** [comment]
@chantastic The generated real is wrong btw, it’s comma separated but should be space separated. That seems like another bug. What are you using to generate the HTML?

**Comment by wooorm** [comment]
@chantastic `rel`* argh
