### ISSUE TITLE
Whitelisting domains?

### ISSUE THREAD

**Issue by zslabs** [remarkjs/remark-external-links#5]
👋 Thanks for creating this! I work with a team that creates content on a fairly regular basis; and unfortunately it'd be easier said then done to tell them to use just relative links for their internal links, but most do use a fully qualified domain; which at the moment - the regex sees as an external one. Any opinion on if you think that'd be a good feature to add?

**Comment by wooorm** [comment]
Hmm, interesting! You could also create a plugin that “relativises” URLs based on a given domain! Something like this plugin, but rewriting the URLs based on a `base` url?

**Comment by zslabs** [comment]
@wooorm Good idea! Until I publish a repo, here's what I ended up using (for anyone else reading this later; I put this in before `remark-external-links`:

```
const visit = require('unist-util-visit');

module.exports = (options = {}) => {
  if (!options.domainRegex) {
    throw Error('Missing required "domainRegex" option');
  }

  function visitor(node) {
    if (options.domainRegex.test(node.url)) {
      node.url = node.url.replace(options.domainRegex, '/');
    }
  }

  function transform(tree) {
    visit(tree, 'link', visitor);
    visit(tree, 'linkReference', visitor);
  }

  return transform;
};
```

Example regex: `/http[s]*:\/\/[www.]*google\.com[/]?/`

**Comment by zslabs** [comment]
Created https://github.com/zslabs/remark-relative-links
