### ISSUE TITLE
mailto links (weird behavior)

### ISSUE THREAD

**Issue by zslabs** [remarkjs/remark-external-links#9]
Currently links that start with `mailto:` have the external link options applied; which is an odd behavior as when clicked the mail client is opened, but a blank tab is shown in the browser.

**Comment by wooorm** [comment]
Currently, any URL that starts with a protocol is seen as external (through [here](https://github.com/remarkjs/remark-external-links/blob/3036589f1835964ebf9634fd3af9911fc4a447b7/index.js#L32) and [here](https://github.com/sindresorhus/is-absolute-url/blob/d2fb33c65ae6805df1fcbfb536d122c76c0f3abb/index.js#L7)).

We can go two ways: see every protocol except mailto as absolute, or see only http / https as absolute. What are your thoughts, and benefits / tradeoffs?

/cc @MakeNowJust (last person to touch that line)

**Comment by zslabs** [comment]
Hey @wooorm appreciate the quick reply as always. I could see this being a compounding issue for protocols like `tel:`, `skype:`, etc. A quick google search for all of them brought up https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

Do you think it'd be worth trying to "whitelist" those in that list? I can't personally think of a time you'd want to have any of those protocols open up a new tab, but I'm not familiar with a bunch of 'em.

**Comment by wooorm** [comment]
I’m not really into adding a big list here 😕 So I’m up for allowing just http / https. But I can see potential exceptions in the future (about? blob? more?). Or just ignoring mailto for now and seeing where that goes?

**Comment by zslabs** [comment]
Yeah maybe just checking for `http/https` would be best for now; as I could make the same argument for a number of those in that list.

**Comment by wooorm** [comment]
Hmm, also like to add that people can set up `mailto:` to open in the browser (such as in Gmail or so). In which case the `target=_blank` definitely makes sense.

**Comment by zslabs** [comment]
> Hmm, also like to add that people can set up `mailto:` to open in the browser (such as in Gmail or so). In which case the `target=_blank` definitely makes sense.

While I do agree there can be different cases for protocol URLs, I myself have never seen a `target="blank"` attached to a `mailto:` link; and is something they can easily customize on their own by just writing out the link as regular HTML if needed.

**Comment by wooorm** [comment]
How about the following pseudo-code changes?

* `var defaultProtocols = ['http', 'https']`
* `var protocols = opts.protocols || defaultProtocols`
* `if (ctx && isAbsoluteURL(ctx.url) && protocols.indexOf(ctx.url.slice(0, ctx.url.indexOf(':')) !== -1)) {`

...that would allow people to still specify their own protocols.

@zslabs Want to write a PR for this, with tests?

**Comment by xuopled** [comment]
It sounds good to me @wooorm
